apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-plugins-config
data:
  conf.yaml: |
    sync:
      connection:
        host: redis-service
    options:
        antispamUrl: http://localhost:11334
