apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-job
  labels:
    app: init-db
spec:
  template:
    metadata:
      labels:
        app: init-db
    spec:
      containers:
      - name: init-mydb
        image: olam1k0/gromox-core:v0.0.1
        imagePullPolicy: Always
        command: ['sh', '-c', "gromox-dbop -C"]
        envFrom:
        - configMapRef:
            name: db-config
      restartPolicy: Never
  backoffLimit: 6
