apiVersion: apps/v1
kind: Deployment
metadata:
  name: gromox-deployment
  labels:
    app: gromox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gromox
  template:
    metadata:
      labels:
        app: gromox
    spec:
      containers:
      - name: gromox-core
        image: olam1k0/gromox-core:0.0.7
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: general-config
        volumeMounts:
        - name: ssl-volume
          mountPath: /home/certificates
        - name: gromox-services-volume
          mountPath: /home/gromox-services
        - name: admin-plugins-volume
          mountPath: /home/plugins
        - name: admin-links-volume
          mountPath: /home/links 
        - name: chat-setup-volume
          mountPath: /home/chat
      volumes:
      - name: ssl-volume
        secret:
          secretName: selfsigned-cert-tls
      - name: admin-plugins-volume
        configMap:
          name: admin-plugins-config
          defaultMode: 0777 
      - name: admin-links-volume
        configMap:
          name: admin-links-config
          defaultMode: 0777
      - name: chat-setup-volume
        configMap:
          name: chat-setup-config
          defaultMode: 0777
      - name: gromox-services-volume
        configMap:
          name: gromox-services-config
---
apiVersion: v1
kind: Service
metadata:
  name: gromox-service
spec:
  selector:
    app: gromox
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: admin
    protocol: TCP
    port: 8443
    targetPort: 8443
